### ISSUE TITLE
Visualizing results

### ISSUE THREAD

**Issue by lukkio88** [wangyu9/steklov-code#1]
Hi,

I've run the `eigen-example.py` and the output, in the docker container is a `result-sphere.mat`. Can you tell me how to visualize the results?

In the code there's also:

```
import eigen_solver as es
import scipy.io as sio

# load mesh
model = 'sphere4.mat'
mat = sio.loadmat(model)
V, F = mat['V'], mat['F']

# solve eigen problem
output = es.steklov_eigen_solver(V,F,num_iter=25,top_k=49)
w_S, v_S = output.w_S, output.v_S
# w_S and v_S are resulting eigenvalues and eigenvectors.

# save results
folder = './result-' + model
es.save_eigen_ouput(folder,output)

# plot results, does not work for command line usage.
if False:
    import matplotlib.pyplot as plt
    plt.figure()
    plt.plot(range(49), output.w_S)
```

I can't figure why nothing is visualized, you explicity say `does not work for command line usage`. How should I use it?

Switching the flag to `True` yields:

```

Traceback (most recent call last):
  File "example_eigen.py", line 21, in <module>
    plt.figure()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1818, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

```

How else am I suppose to run it?

Regards

**Comment by wangyu9** [comment]
Hi, 
The docker container is like a light-weight virtual machine without display device by default. The visualization code is not supposed to be used in the docker container. 
There are a bit complicated solutions online: https://stackoverflow.com/questions/46018102/how-can-i-use-matplotlib-pyplot-in-a-docker-container
The simplest solution is probably just to use the provided code to compute eigenfunctions and save the results in *.mat file, and then load the file and run any visualization function *outside* the docker container.  
Regards

**Comment by lukkio88** [comment]
I'm not particularly familiar with docker. I'll try to move the result file from the docker container to my linux machine and then visualize it, I'll try to use the solution given in the post you pointed out as well

**Comment by lukkio88** [comment]
One more question, what exactly are the dependencies I'd need to install if I wanted to run your code without docker?

**Comment by wangyu9** [comment]
Basically libdune, numpy, scipy, bempp, and their dependencies. See Dockerfile for a complete list and the recommended versions I have tested with.

**Comment by wangyu9** [comment]
To transfer files to your local machine, one simple way is to mount a local folder to the container using the docker -v option: 

sudo docker run -it steklov-py2 -v SOME_PATH_ON_LOCAL_MACHINE:SOME_PATH_ON_CONTAINTER

**Comment by lukkio88** [comment]
Perfect. One side question (I can open a new issue in case) can your code be used for feature extraction on a mesh? Is this something you've tried?

**Comment by wangyu9** [comment]
Yes, the top k eigenfunctions already give you a k-dimensional feature vector pervertex. 
Or you can constructed more sophisticated pervertex features like the heat kernel signature: 

https://github.com/wangyu9/steklov-code/blob/fcf6a12bed1d2dfda0d9449235070bb4b2937482/include/bempp_operator.py#L420

Please refer to our paper for experiments: https://dl.acm.org/citation.cfm?id=3152156

**Comment by lukkio88** [comment]
Hi, very last question. I managed to visualize the result by moving the result from the container to my machine, however can I was wondering if you can suggest an easy way to convert an .obj into a .mat file so I can reuse your example code to see how the eigen functions look like.
